/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoApolloClientRouteImport } from './routes/demo.apollo-client'
import { Route as AdminWarehouseMapRouteImport } from './routes/admin/warehouse-map'
import { Route as AdminUserManagementRouteImport } from './routes/admin/user-management'
import { Route as AdminTransportRouteImport } from './routes/admin/transport'
import { Route as AdminStockTransferRouteImport } from './routes/admin/stock-transfer'
import { Route as AdminStockQuantRouteImport } from './routes/admin/stock-quant'
import { Route as AdminStockAdjustmentRouteImport } from './routes/admin/stock-adjustment'
import { Route as AdminSkuMovementRouteImport } from './routes/admin/sku-movement'
import { Route as AdminSkuAssignmentsRouteImport } from './routes/admin/sku-assignments'
import { Route as AdminSetupAreaRouteImport } from './routes/admin/setup-area'
import { Route as AdminSettlementRouteImport } from './routes/admin/settlement'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRbacRouteImport } from './routes/admin/rbac'
import { Route as AdminRacksRouteImport } from './routes/admin/racks'
import { Route as AdminPutawayRouteImport } from './routes/admin/putaway'
import { Route as AdminProofOfDeliveryRouteImport } from './routes/admin/proof-of-delivery'
import { Route as AdminPickingCriteriaRouteImport } from './routes/admin/picking-criteria'
import { Route as AdminPickFaceStrategyRouteImport } from './routes/admin/pick-face-strategy'
import { Route as AdminPalletLabelsRouteImport } from './routes/admin/pallet-labels'
import { Route as AdminOutboundRouteImport } from './routes/admin/outbound'
import { Route as AdminMovementCrossCheckRouteImport } from './routes/admin/movement-cross-check'
import { Route as AdminItemsRouteImport } from './routes/admin/items'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminInvoiceDetailRouteImport } from './routes/admin/invoice-detail'
import { Route as AdminInventoryDetailRouteImport } from './routes/admin/inventory-detail'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminGrnRemainingReportRouteImport } from './routes/admin/grn-remaining-report'
import { Route as AdminGrnRouteImport } from './routes/admin/grn'
import { Route as AdminForbiddenRouteImport } from './routes/admin/forbidden'
import { Route as AdminExceptionsRouteImport } from './routes/admin/exceptions'
import { Route as AdminExceptionDetailRouteImport } from './routes/admin/exception-detail'
import { Route as AdminEsDoRouteImport } from './routes/admin/es-do'
import { Route as AdminDoWorkQueueRouteImport } from './routes/admin/do-work-queue'
import { Route as AdminDoDetailRouteImport } from './routes/admin/do-detail'
import { Route as AdminDeliveriesRouteImport } from './routes/admin/deliveries'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBinTransferWorkQueueRouteImport } from './routes/admin/bin-transfer-work-queue'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminApiLogRouteImport } from './routes/admin/api-log'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminSettlementIdRouteImport } from './routes/admin/settlement.$id'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApolloClientRoute = DemoApolloClientRouteImport.update({
  id: '/demo/apollo-client',
  path: '/demo/apollo-client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseMapRoute = AdminWarehouseMapRouteImport.update({
  id: '/warehouse-map',
  path: '/warehouse-map',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockTransferRoute = AdminStockTransferRouteImport.update({
  id: '/stock-transfer',
  path: '/stock-transfer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockQuantRoute = AdminStockQuantRouteImport.update({
  id: '/stock-quant',
  path: '/stock-quant',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockAdjustmentRoute = AdminStockAdjustmentRouteImport.update({
  id: '/stock-adjustment',
  path: '/stock-adjustment',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkuMovementRoute = AdminSkuMovementRouteImport.update({
  id: '/sku-movement',
  path: '/sku-movement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkuAssignmentsRoute = AdminSkuAssignmentsRouteImport.update({
  id: '/sku-assignments',
  path: '/sku-assignments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSetupAreaRoute = AdminSetupAreaRouteImport.update({
  id: '/setup-area',
  path: '/setup-area',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettlementRoute = AdminSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRacksRoute = AdminRacksRouteImport.update({
  id: '/racks',
  path: '/racks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPutawayRoute = AdminPutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProofOfDeliveryRoute = AdminProofOfDeliveryRouteImport.update({
  id: '/proof-of-delivery',
  path: '/proof-of-delivery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPickingCriteriaRoute = AdminPickingCriteriaRouteImport.update({
  id: '/picking-criteria',
  path: '/picking-criteria',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPickFaceStrategyRoute = AdminPickFaceStrategyRouteImport.update({
  id: '/pick-face-strategy',
  path: '/pick-face-strategy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPalletLabelsRoute = AdminPalletLabelsRouteImport.update({
  id: '/pallet-labels',
  path: '/pallet-labels',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOutboundRoute = AdminOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMovementCrossCheckRoute = AdminMovementCrossCheckRouteImport.update({
  id: '/movement-cross-check',
  path: '/movement-cross-check',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoiceDetailRoute = AdminInvoiceDetailRouteImport.update({
  id: '/invoice-detail',
  path: '/invoice-detail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryDetailRoute = AdminInventoryDetailRouteImport.update({
  id: '/inventory-detail',
  path: '/inventory-detail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGrnRemainingReportRoute = AdminGrnRemainingReportRouteImport.update({
  id: '/grn-remaining-report',
  path: '/grn-remaining-report',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGrnRoute = AdminGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForbiddenRoute = AdminForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExceptionsRoute = AdminExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExceptionDetailRoute = AdminExceptionDetailRouteImport.update({
  id: '/exception-detail',
  path: '/exception-detail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEsDoRoute = AdminEsDoRouteImport.update({
  id: '/es-do',
  path: '/es-do',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoWorkQueueRoute = AdminDoWorkQueueRouteImport.update({
  id: '/do-work-queue',
  path: '/do-work-queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoDetailRoute = AdminDoDetailRouteImport.update({
  id: '/do-detail',
  path: '/do-detail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBinTransferWorkQueueRoute =
  AdminBinTransferWorkQueueRouteImport.update({
    id: '/bin-transfer-work-queue',
    path: '/bin-transfer-work-queue',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiLogRoute = AdminApiLogRouteImport.update({
  id: '/api-log',
  path: '/api-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementIdRoute = AdminSettlementIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSettlementRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-log': typeof AdminApiLogRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/bin-transfer-work-queue': typeof AdminBinTransferWorkQueueRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/do-detail': typeof AdminDoDetailRoute
  '/admin/do-work-queue': typeof AdminDoWorkQueueRoute
  '/admin/es-do': typeof AdminEsDoRoute
  '/admin/exception-detail': typeof AdminExceptionDetailRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/grn': typeof AdminGrnRoute
  '/admin/grn-remaining-report': typeof AdminGrnRemainingReportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/inventory-detail': typeof AdminInventoryDetailRoute
  '/admin/invoice-detail': typeof AdminInvoiceDetailRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/movement-cross-check': typeof AdminMovementCrossCheckRoute
  '/admin/outbound': typeof AdminOutboundRoute
  '/admin/pallet-labels': typeof AdminPalletLabelsRoute
  '/admin/pick-face-strategy': typeof AdminPickFaceStrategyRoute
  '/admin/picking-criteria': typeof AdminPickingCriteriaRoute
  '/admin/proof-of-delivery': typeof AdminProofOfDeliveryRoute
  '/admin/putaway': typeof AdminPutawayRoute
  '/admin/racks': typeof AdminRacksRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlement': typeof AdminSettlementRouteWithChildren
  '/admin/setup-area': typeof AdminSetupAreaRoute
  '/admin/sku-assignments': typeof AdminSkuAssignmentsRoute
  '/admin/sku-movement': typeof AdminSkuMovementRoute
  '/admin/stock-adjustment': typeof AdminStockAdjustmentRoute
  '/admin/stock-quant': typeof AdminStockQuantRoute
  '/admin/stock-transfer': typeof AdminStockTransferRoute
  '/admin/transport': typeof AdminTransportRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/admin/warehouse-map': typeof AdminWarehouseMapRoute
  '/demo/apollo-client': typeof DemoApolloClientRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/settlement/$id': typeof AdminSettlementIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-log': typeof AdminApiLogRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/bin-transfer-work-queue': typeof AdminBinTransferWorkQueueRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/do-detail': typeof AdminDoDetailRoute
  '/admin/do-work-queue': typeof AdminDoWorkQueueRoute
  '/admin/es-do': typeof AdminEsDoRoute
  '/admin/exception-detail': typeof AdminExceptionDetailRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/grn': typeof AdminGrnRoute
  '/admin/grn-remaining-report': typeof AdminGrnRemainingReportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/inventory-detail': typeof AdminInventoryDetailRoute
  '/admin/invoice-detail': typeof AdminInvoiceDetailRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/movement-cross-check': typeof AdminMovementCrossCheckRoute
  '/admin/outbound': typeof AdminOutboundRoute
  '/admin/pallet-labels': typeof AdminPalletLabelsRoute
  '/admin/pick-face-strategy': typeof AdminPickFaceStrategyRoute
  '/admin/picking-criteria': typeof AdminPickingCriteriaRoute
  '/admin/proof-of-delivery': typeof AdminProofOfDeliveryRoute
  '/admin/putaway': typeof AdminPutawayRoute
  '/admin/racks': typeof AdminRacksRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlement': typeof AdminSettlementRouteWithChildren
  '/admin/setup-area': typeof AdminSetupAreaRoute
  '/admin/sku-assignments': typeof AdminSkuAssignmentsRoute
  '/admin/sku-movement': typeof AdminSkuMovementRoute
  '/admin/stock-adjustment': typeof AdminStockAdjustmentRoute
  '/admin/stock-quant': typeof AdminStockQuantRoute
  '/admin/stock-transfer': typeof AdminStockTransferRoute
  '/admin/transport': typeof AdminTransportRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/admin/warehouse-map': typeof AdminWarehouseMapRoute
  '/demo/apollo-client': typeof DemoApolloClientRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/settlement/$id': typeof AdminSettlementIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-log': typeof AdminApiLogRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/bin-transfer-work-queue': typeof AdminBinTransferWorkQueueRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/do-detail': typeof AdminDoDetailRoute
  '/admin/do-work-queue': typeof AdminDoWorkQueueRoute
  '/admin/es-do': typeof AdminEsDoRoute
  '/admin/exception-detail': typeof AdminExceptionDetailRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/grn': typeof AdminGrnRoute
  '/admin/grn-remaining-report': typeof AdminGrnRemainingReportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/inventory-detail': typeof AdminInventoryDetailRoute
  '/admin/invoice-detail': typeof AdminInvoiceDetailRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/movement-cross-check': typeof AdminMovementCrossCheckRoute
  '/admin/outbound': typeof AdminOutboundRoute
  '/admin/pallet-labels': typeof AdminPalletLabelsRoute
  '/admin/pick-face-strategy': typeof AdminPickFaceStrategyRoute
  '/admin/picking-criteria': typeof AdminPickingCriteriaRoute
  '/admin/proof-of-delivery': typeof AdminProofOfDeliveryRoute
  '/admin/putaway': typeof AdminPutawayRoute
  '/admin/racks': typeof AdminRacksRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlement': typeof AdminSettlementRouteWithChildren
  '/admin/setup-area': typeof AdminSetupAreaRoute
  '/admin/sku-assignments': typeof AdminSkuAssignmentsRoute
  '/admin/sku-movement': typeof AdminSkuMovementRoute
  '/admin/stock-adjustment': typeof AdminStockAdjustmentRoute
  '/admin/stock-quant': typeof AdminStockQuantRoute
  '/admin/stock-transfer': typeof AdminStockTransferRoute
  '/admin/transport': typeof AdminTransportRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/admin/warehouse-map': typeof AdminWarehouseMapRoute
  '/demo/apollo-client': typeof DemoApolloClientRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/settlement/$id': typeof AdminSettlementIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/api-keys'
    | '/admin/api-log'
    | '/admin/audit-log'
    | '/admin/bin-transfer-work-queue'
    | '/admin/dashboard'
    | '/admin/deliveries'
    | '/admin/do-detail'
    | '/admin/do-work-queue'
    | '/admin/es-do'
    | '/admin/exception-detail'
    | '/admin/exceptions'
    | '/admin/forbidden'
    | '/admin/grn'
    | '/admin/grn-remaining-report'
    | '/admin/inventory'
    | '/admin/inventory-detail'
    | '/admin/invoice-detail'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/movement-cross-check'
    | '/admin/outbound'
    | '/admin/pallet-labels'
    | '/admin/pick-face-strategy'
    | '/admin/picking-criteria'
    | '/admin/proof-of-delivery'
    | '/admin/putaway'
    | '/admin/racks'
    | '/admin/rbac'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/settlement'
    | '/admin/setup-area'
    | '/admin/sku-assignments'
    | '/admin/sku-movement'
    | '/admin/stock-adjustment'
    | '/admin/stock-quant'
    | '/admin/stock-transfer'
    | '/admin/transport'
    | '/admin/user-management'
    | '/admin/warehouse-map'
    | '/demo/apollo-client'
    | '/demo/i18n'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin/settlement/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/api-keys'
    | '/admin/api-log'
    | '/admin/audit-log'
    | '/admin/bin-transfer-work-queue'
    | '/admin/dashboard'
    | '/admin/deliveries'
    | '/admin/do-detail'
    | '/admin/do-work-queue'
    | '/admin/es-do'
    | '/admin/exception-detail'
    | '/admin/exceptions'
    | '/admin/forbidden'
    | '/admin/grn'
    | '/admin/grn-remaining-report'
    | '/admin/inventory'
    | '/admin/inventory-detail'
    | '/admin/invoice-detail'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/movement-cross-check'
    | '/admin/outbound'
    | '/admin/pallet-labels'
    | '/admin/pick-face-strategy'
    | '/admin/picking-criteria'
    | '/admin/proof-of-delivery'
    | '/admin/putaway'
    | '/admin/racks'
    | '/admin/rbac'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/settlement'
    | '/admin/setup-area'
    | '/admin/sku-assignments'
    | '/admin/sku-movement'
    | '/admin/stock-adjustment'
    | '/admin/stock-quant'
    | '/admin/stock-transfer'
    | '/admin/transport'
    | '/admin/user-management'
    | '/admin/warehouse-map'
    | '/demo/apollo-client'
    | '/demo/i18n'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin/settlement/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/api-keys'
    | '/admin/api-log'
    | '/admin/audit-log'
    | '/admin/bin-transfer-work-queue'
    | '/admin/dashboard'
    | '/admin/deliveries'
    | '/admin/do-detail'
    | '/admin/do-work-queue'
    | '/admin/es-do'
    | '/admin/exception-detail'
    | '/admin/exceptions'
    | '/admin/forbidden'
    | '/admin/grn'
    | '/admin/grn-remaining-report'
    | '/admin/inventory'
    | '/admin/inventory-detail'
    | '/admin/invoice-detail'
    | '/admin/invoices'
    | '/admin/items'
    | '/admin/movement-cross-check'
    | '/admin/outbound'
    | '/admin/pallet-labels'
    | '/admin/pick-face-strategy'
    | '/admin/picking-criteria'
    | '/admin/proof-of-delivery'
    | '/admin/putaway'
    | '/admin/racks'
    | '/admin/rbac'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/settlement'
    | '/admin/setup-area'
    | '/admin/sku-assignments'
    | '/admin/sku-movement'
    | '/admin/stock-adjustment'
    | '/admin/stock-quant'
    | '/admin/stock-transfer'
    | '/admin/transport'
    | '/admin/user-management'
    | '/admin/warehouse-map'
    | '/demo/apollo-client'
    | '/demo/i18n'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin/settlement/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DemoApolloClientRoute: typeof DemoApolloClientRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/apollo-client': {
      id: '/demo/apollo-client'
      path: '/demo/apollo-client'
      fullPath: '/demo/apollo-client'
      preLoaderRoute: typeof DemoApolloClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse-map': {
      id: '/admin/warehouse-map'
      path: '/warehouse-map'
      fullPath: '/admin/warehouse-map'
      preLoaderRoute: typeof AdminWarehouseMapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock-transfer': {
      id: '/admin/stock-transfer'
      path: '/stock-transfer'
      fullPath: '/admin/stock-transfer'
      preLoaderRoute: typeof AdminStockTransferRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock-quant': {
      id: '/admin/stock-quant'
      path: '/stock-quant'
      fullPath: '/admin/stock-quant'
      preLoaderRoute: typeof AdminStockQuantRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock-adjustment': {
      id: '/admin/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/admin/stock-adjustment'
      preLoaderRoute: typeof AdminStockAdjustmentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sku-movement': {
      id: '/admin/sku-movement'
      path: '/sku-movement'
      fullPath: '/admin/sku-movement'
      preLoaderRoute: typeof AdminSkuMovementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sku-assignments': {
      id: '/admin/sku-assignments'
      path: '/sku-assignments'
      fullPath: '/admin/sku-assignments'
      preLoaderRoute: typeof AdminSkuAssignmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/setup-area': {
      id: '/admin/setup-area'
      path: '/setup-area'
      fullPath: '/admin/setup-area'
      preLoaderRoute: typeof AdminSetupAreaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settlement': {
      id: '/admin/settlement'
      path: '/settlement'
      fullPath: '/admin/settlement'
      preLoaderRoute: typeof AdminSettlementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/racks': {
      id: '/admin/racks'
      path: '/racks'
      fullPath: '/admin/racks'
      preLoaderRoute: typeof AdminRacksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/putaway': {
      id: '/admin/putaway'
      path: '/putaway'
      fullPath: '/admin/putaway'
      preLoaderRoute: typeof AdminPutawayRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/proof-of-delivery': {
      id: '/admin/proof-of-delivery'
      path: '/proof-of-delivery'
      fullPath: '/admin/proof-of-delivery'
      preLoaderRoute: typeof AdminProofOfDeliveryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/picking-criteria': {
      id: '/admin/picking-criteria'
      path: '/picking-criteria'
      fullPath: '/admin/picking-criteria'
      preLoaderRoute: typeof AdminPickingCriteriaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pick-face-strategy': {
      id: '/admin/pick-face-strategy'
      path: '/pick-face-strategy'
      fullPath: '/admin/pick-face-strategy'
      preLoaderRoute: typeof AdminPickFaceStrategyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pallet-labels': {
      id: '/admin/pallet-labels'
      path: '/pallet-labels'
      fullPath: '/admin/pallet-labels'
      preLoaderRoute: typeof AdminPalletLabelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/outbound': {
      id: '/admin/outbound'
      path: '/outbound'
      fullPath: '/admin/outbound'
      preLoaderRoute: typeof AdminOutboundRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/movement-cross-check': {
      id: '/admin/movement-cross-check'
      path: '/movement-cross-check'
      fullPath: '/admin/movement-cross-check'
      preLoaderRoute: typeof AdminMovementCrossCheckRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoice-detail': {
      id: '/admin/invoice-detail'
      path: '/invoice-detail'
      fullPath: '/admin/invoice-detail'
      preLoaderRoute: typeof AdminInvoiceDetailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory-detail': {
      id: '/admin/inventory-detail'
      path: '/inventory-detail'
      fullPath: '/admin/inventory-detail'
      preLoaderRoute: typeof AdminInventoryDetailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grn-remaining-report': {
      id: '/admin/grn-remaining-report'
      path: '/grn-remaining-report'
      fullPath: '/admin/grn-remaining-report'
      preLoaderRoute: typeof AdminGrnRemainingReportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grn': {
      id: '/admin/grn'
      path: '/grn'
      fullPath: '/admin/grn'
      preLoaderRoute: typeof AdminGrnRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forbidden': {
      id: '/admin/forbidden'
      path: '/forbidden'
      fullPath: '/admin/forbidden'
      preLoaderRoute: typeof AdminForbiddenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exceptions': {
      id: '/admin/exceptions'
      path: '/exceptions'
      fullPath: '/admin/exceptions'
      preLoaderRoute: typeof AdminExceptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exception-detail': {
      id: '/admin/exception-detail'
      path: '/exception-detail'
      fullPath: '/admin/exception-detail'
      preLoaderRoute: typeof AdminExceptionDetailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/es-do': {
      id: '/admin/es-do'
      path: '/es-do'
      fullPath: '/admin/es-do'
      preLoaderRoute: typeof AdminEsDoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/do-work-queue': {
      id: '/admin/do-work-queue'
      path: '/do-work-queue'
      fullPath: '/admin/do-work-queue'
      preLoaderRoute: typeof AdminDoWorkQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/do-detail': {
      id: '/admin/do-detail'
      path: '/do-detail'
      fullPath: '/admin/do-detail'
      preLoaderRoute: typeof AdminDoDetailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bin-transfer-work-queue': {
      id: '/admin/bin-transfer-work-queue'
      path: '/bin-transfer-work-queue'
      fullPath: '/admin/bin-transfer-work-queue'
      preLoaderRoute: typeof AdminBinTransferWorkQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-log': {
      id: '/admin/api-log'
      path: '/api-log'
      fullPath: '/admin/api-log'
      preLoaderRoute: typeof AdminApiLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlement/$id': {
      id: '/admin/settlement/$id'
      path: '/$id'
      fullPath: '/admin/settlement/$id'
      preLoaderRoute: typeof AdminSettlementIdRouteImport
      parentRoute: typeof AdminSettlementRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSettlementRouteChildren {
  AdminSettlementIdRoute: typeof AdminSettlementIdRoute
}

const AdminSettlementRouteChildren: AdminSettlementRouteChildren = {
  AdminSettlementIdRoute: AdminSettlementIdRoute,
}

const AdminSettlementRouteWithChildren = AdminSettlementRoute._addFileChildren(
  AdminSettlementRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminApiLogRoute: typeof AdminApiLogRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBinTransferWorkQueueRoute: typeof AdminBinTransferWorkQueueRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminDoDetailRoute: typeof AdminDoDetailRoute
  AdminDoWorkQueueRoute: typeof AdminDoWorkQueueRoute
  AdminEsDoRoute: typeof AdminEsDoRoute
  AdminExceptionDetailRoute: typeof AdminExceptionDetailRoute
  AdminExceptionsRoute: typeof AdminExceptionsRoute
  AdminForbiddenRoute: typeof AdminForbiddenRoute
  AdminGrnRoute: typeof AdminGrnRoute
  AdminGrnRemainingReportRoute: typeof AdminGrnRemainingReportRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminInventoryDetailRoute: typeof AdminInventoryDetailRoute
  AdminInvoiceDetailRoute: typeof AdminInvoiceDetailRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminMovementCrossCheckRoute: typeof AdminMovementCrossCheckRoute
  AdminOutboundRoute: typeof AdminOutboundRoute
  AdminPalletLabelsRoute: typeof AdminPalletLabelsRoute
  AdminPickFaceStrategyRoute: typeof AdminPickFaceStrategyRoute
  AdminPickingCriteriaRoute: typeof AdminPickingCriteriaRoute
  AdminProofOfDeliveryRoute: typeof AdminProofOfDeliveryRoute
  AdminPutawayRoute: typeof AdminPutawayRoute
  AdminRacksRoute: typeof AdminRacksRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSettlementRoute: typeof AdminSettlementRouteWithChildren
  AdminSetupAreaRoute: typeof AdminSetupAreaRoute
  AdminSkuAssignmentsRoute: typeof AdminSkuAssignmentsRoute
  AdminSkuMovementRoute: typeof AdminSkuMovementRoute
  AdminStockAdjustmentRoute: typeof AdminStockAdjustmentRoute
  AdminStockQuantRoute: typeof AdminStockQuantRoute
  AdminStockTransferRoute: typeof AdminStockTransferRoute
  AdminTransportRoute: typeof AdminTransportRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  AdminWarehouseMapRoute: typeof AdminWarehouseMapRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminApiLogRoute: AdminApiLogRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBinTransferWorkQueueRoute: AdminBinTransferWorkQueueRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminDoDetailRoute: AdminDoDetailRoute,
  AdminDoWorkQueueRoute: AdminDoWorkQueueRoute,
  AdminEsDoRoute: AdminEsDoRoute,
  AdminExceptionDetailRoute: AdminExceptionDetailRoute,
  AdminExceptionsRoute: AdminExceptionsRoute,
  AdminForbiddenRoute: AdminForbiddenRoute,
  AdminGrnRoute: AdminGrnRoute,
  AdminGrnRemainingReportRoute: AdminGrnRemainingReportRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminInventoryDetailRoute: AdminInventoryDetailRoute,
  AdminInvoiceDetailRoute: AdminInvoiceDetailRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminMovementCrossCheckRoute: AdminMovementCrossCheckRoute,
  AdminOutboundRoute: AdminOutboundRoute,
  AdminPalletLabelsRoute: AdminPalletLabelsRoute,
  AdminPickFaceStrategyRoute: AdminPickFaceStrategyRoute,
  AdminPickingCriteriaRoute: AdminPickingCriteriaRoute,
  AdminProofOfDeliveryRoute: AdminProofOfDeliveryRoute,
  AdminPutawayRoute: AdminPutawayRoute,
  AdminRacksRoute: AdminRacksRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSettlementRoute: AdminSettlementRouteWithChildren,
  AdminSetupAreaRoute: AdminSetupAreaRoute,
  AdminSkuAssignmentsRoute: AdminSkuAssignmentsRoute,
  AdminSkuMovementRoute: AdminSkuMovementRoute,
  AdminStockAdjustmentRoute: AdminStockAdjustmentRoute,
  AdminStockQuantRoute: AdminStockQuantRoute,
  AdminStockTransferRoute: AdminStockTransferRoute,
  AdminTransportRoute: AdminTransportRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  AdminWarehouseMapRoute: AdminWarehouseMapRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DemoApolloClientRoute: DemoApolloClientRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
